export interface City {
  id: number;
  name: string;
  altNames: string[];
  lat: number;
  lon: number;
}

export const cities: City[] = [
  {
    id: 1,
    name: "São Paulo",
    altNames: ["SP", "Sampa"],
    lat: -23.55,
    lon: -46.63,
  },
  {
    id: 2,
    name: "Rio de Janeiro",
    altNames: ["RJ", "Rio"],
    lat: -22.91,
    lon: -43.17,
  },
  {
    id: 3,
    name: "Salvador",
    altNames: ["SSA", "Bahia"],
    lat: -12.97,
    lon: -38.5,
  },
  {
    id: 4,
    name: "Brasília",
    altNames: ["BSB", "DF"],
    lat: -15.78,
    lon: -47.93,
  },
  {
    id: 5,
    name: "Fortaleza",
    altNames: ["FOR", "Ceará"],
    lat: -3.72,
    lon: -38.54,
  },
  {
    id: 6,
    name: "Belo Horizonte",
    altNames: ["BH", "Minas"],
    lat: -19.92,
    lon: -43.94,
  },
  {
    id: 7,
    name: "Manaus",
    altNames: ["MAO", "Amazonas"],
    lat: -3.1,
    lon: -60.02,
  },
  {
    id: 8,
    name: "Curitiba",
    altNames: ["CWB", "Paraná"],
    lat: -25.42,
    lon: -49.27,
  },
  {
    id: 9,
    name: "Recife",
    altNames: ["REC", "Pernambuco"],
    lat: -8.05,
    lon: -34.88,
  },
  {
    id: 10,
    name: "Porto Alegre",
    altNames: ["POA", "RS"],
    lat: -30.03,
    lon: -51.23,
  },
  { id: 11, name: "Belém", altNames: ["BEL", "Pará"], lat: -1.45, lon: -48.5 },
  {
    id: 12,
    name: "Goiânia",
    altNames: ["GYN", "Goiás"],
    lat: -16.68,
    lon: -49.25,
  },
  { id: 13, name: "Guarulhos", altNames: ["GRU"], lat: -23.46, lon: -46.53 },
  { id: 14, name: "Campinas", altNames: ["VCP"], lat: -22.9, lon: -47.06 },
  {
    id: 15,
    name: "São Luís",
    altNames: ["SLZ", "Maranhão"],
    lat: -2.53,
    lon: -44.3,
  },
  {
    id: 16,
    name: "Maceió",
    altNames: ["MCZ", "Alagoas"],
    lat: -9.66,
    lon: -35.73,
  },
  {
    id: 17,
    name: "Duque de Caxias",
    altNames: ["Caxias"],
    lat: -22.79,
    lon: -43.31,
  },
  { id: 18, name: "Natal", altNames: ["NAT", "RN"], lat: -5.79, lon: -35.2 },
  {
    id: 19,
    name: "Teresina",
    altNames: ["THE", "Piauí"],
    lat: -5.09,
    lon: -42.8,
  },
  {
    id: 20,
    name: "Campo Grande",
    altNames: ["CGR", "MS"],
    lat: -20.44,
    lon: -54.65,
  },
  {
    id: 21,
    name: "João Pessoa",
    altNames: ["JPA", "PB"],
    lat: -7.12,
    lon: -34.86,
  },
  {
    id: 22,
    name: "Jaboatão dos Guararapes",
    altNames: ["Jaboatão"],
    lat: -8.11,
    lon: -35.01,
  },
  { id: 23, name: "Santo André", altNames: ["SA"], lat: -23.66, lon: -46.53 },
  { id: 24, name: "Osasco", altNames: [], lat: -23.53, lon: -46.79 },
  {
    id: 25,
    name: "São Bernardo do Campo",
    altNames: ["SBC"],
    lat: -23.69,
    lon: -46.56,
  },
  { id: 26, name: "Contagem", altNames: [], lat: -19.93, lon: -44.05 },
  { id: 27, name: "Uberlândia", altNames: ["UDI"], lat: -18.92, lon: -48.28 },
  { id: 28, name: "Sorocaba", altNames: [], lat: -23.5, lon: -47.46 },
  {
    id: 29,
    name: "Aracaju",
    altNames: ["AJU", "Sergipe"],
    lat: -10.91,
    lon: -37.07,
  },
  {
    id: 30,
    name: "Feira de Santana",
    altNames: ["Feira"],
    lat: -12.27,
    lon: -38.97,
  },
];
